name: Build and test master

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  build_and_test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Build on ${{ matrix.os }}
        run: go build -v -a .

      - name: Test on ${{ matrix.os }}
        run: go test -v ./...
